global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: "fastapi"
    static_configs:
      - targets: ["api:8000"]
    metrics_path: "/metrics"
    scrape_timeout: 3s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: "fastapi"
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: "go_.*"
        action: drop
