apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    uid: prometheus
    isDefault: true
    jsonData:
      timeInterval: "5s"
      queryTimeout: "30s"
      httpMethod: "GET"
      exemplarTraceIdDestinations:
        - name: traceID
          datasourceUid: prometheus
    version: 1
    editable: true
